import { Header } from "@/components/Header";
import Head from "next/head";

export default function About() {
  return (
    <>
      <Head>
        <title>Joselin Vargas | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="Portfolio">
        <Header />

        <div className="about">
          <h2>About me</h2>

          <p>
            ¡Hola! Soy Joselin Vargas, una fotógrafa especializada en fotos de
            estudio y productos de comida. Me apasiona capturar momentos y
            emociones a través de mi lente y transformarlos en imágenes
            duraderas que puedan ser disfrutadas durante años.
          </p>
          <p>
            Mi enfoque principal es retratar a mis clientes de la manera más
            auténtica y natural posible. Me esfuerzo por crear un ambiente
            relajado y cómodo para que se sientan completamente a gusto durante
            la sesión de fotos. Mi objetivo es que se diviertan y se sientan lo
            más cómodos posible, para que así podamos capturar su verdadera
            esencia.
          </p>
          <p>
            Además de mi habilidad para capturar momentos y emociones, también
            tengo experiencia en fotografiar productos de comida y crear banners
            publicitarios. Disfruto experimentar con diferentes técnicas y
            estilos para crear imágenes que destaquen y reflejen la personalidad
            de cada producto.
          </p>
          <p>
            Si estás buscando un fotógrafo de estudio que pueda capturar la
            esencia de tu marca o producto, ¡no dudes en contactarme! Estoy
            emocionada de trabajar contigo para crear imágenes únicas y hermosas
            que te ayuden a destacarte en el mercado.
          </p>
        </div>
      </main>
    </>
  );
}
