import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="Home">
        <div className="Home-title">
          <Image src="/home-image.jpg" alt="Beach" height={500} width={400} />
          <Link href={"/portfolio"}>
            <h1>Joselin Vargas</h1>
          </Link>

          <Link href={"/portfolio"}>
            <p>Portfolio</p>
          </Link>
        </div>
      </main>
    </>
  );
}
