import { Header } from "@/components/Header";
import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";

import StackGrid, { transitions } from "react-stack-grid";

const { scaleDown } = transitions;

export default function Portfolio() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="Portfolio">
        <Header />

        <div className="Portfolio-container-categories">
          <h4>Categories</h4>

          <StackGrid
            columnWidth={500}
            appear={scaleDown.appear}
            appeared={scaleDown.appeared}
            enter={scaleDown.enter}
            entered={scaleDown.entered}
            leaved={scaleDown.leaved}
            gutterWidth={15}
            gutterHeight={20}
          >
            <div key="key1" className="div one">
              <Link href="portfolio/category">
                <p>Category 1</p>
              </Link>
            </div>
            <div key="key2" className="div two">
              <Link href="portfolio/category">
                <p>Category 2</p>
              </Link>
            </div>
            <div key="key3" className="div three">
              <Link href="portfolio/category">
                <p>Category 3</p>
              </Link>
            </div>
            <div key="key4" className="div four">
              <Link href="portfolio/category">
                <p>Category 4</p>
              </Link>
            </div>
          </StackGrid>
        </div>
      </main>
    </>
  );
}
